### ISSUE TITLE
Symbol replacement isn't greedy enough

### ISSUE THREAD

**Issue by coandco** [chao-master/TSSSFF-Generator#1]
When you type \malefemale into one of the fields, it gets replaced by "(male symbol)female".

**Comment by coandco** [comment]
This could be solved by looking for {symbol}, rather than \symbol -- that way you'd be guaranteed to match a complete entity and not a substring.  I'm attempting to get a local clone of this up and running -- if I do, I'll do a quick patch and throw a pull request your way.

**Comment by coandco** [comment]
Hmm.  Do you have the table-creation SQL commands you used to set this up initially?  I can try to reverse-engineer the table structure from the SELECT statements in dbInterface.php, but it'd be better if I could just get the table structure from the source.

**Comment by coandco** [comment]
Either way, it looks like the frontend functions just fine without the backend setup.  I've submitted a pull request that fixes the problem and corrects a minor spelling error.

**Comment by chao-master** [comment]
I just fixed this! I was like "wait did I make it greedy enough" and I didn't
Fixed by commit f917ff0a in the beta branch.

Full table creation commands will be in the readme when write it up.
