### ISSUE TITLE
Extra letters added when exported

### ISSUE THREAD

**Issue by MrQuallzin** [chao-master/TSSSFF-Generator#17]
A few cards export with extra letters attached to them. It hasn't been for every card I tried, but they are persistent for the ones that have them, meaning re-exporting them does not fix them. 
![card_jackie](https://cloud.githubusercontent.com/assets/3629189/8121263/116ba402-105e-11e5-9d8d-3035699af39b.png)
![card_lemony](https://cloud.githubusercontent.com/assets/3629189/8121264/1173d9ec-105e-11e5-83d0-464b80894c30.png)

**Comment by chao-master** [comment]
Legacy export has been removed. Closing.
