### ISSUE TITLE
Copyright overwritten in export

### ISSUE THREAD

**Issue by MrQuallzin** [chao-master/TSSSFF-Generator#18]
I'm sure it's been noticed, but I'll put it in Issues as to not be forgotten. When exported, cards' Copyright is replaced with "LD⋯C ; TSSSF by Horrible People Games. Art by Pixel Prism."

**Comment by chao-master** [comment]
Yeh it's noted I haven't trolled through enough of the program to know how to fix it let
Exporting has been put on low shelf

**Comment by chao-master** [comment]
Legacy export has been removed. Closing.
