### ISSUE TITLE
Low hanging letters cut off in flavor text

### ISSUE THREAD

**Issue by MrQuallzin** [chao-master/TSSSFF-Generator#26]
Letters such as 'g' and 'y' have their lower portions cut off on the card generator page. This is not an issue once exported.
![capture](https://cloud.githubusercontent.com/assets/3629189/8146160/ab80a358-11df-11e5-8322-0c5405365bcb.PNG)

**Comment by chao-master** [comment]
Could you provide more info and maybe a link to the card that produces the issue as I could not recreate

**Comment by MrQuallzin** [comment]
Here's an example card: http://ripppo.me/TSSSFF-Beta/#view:d634c1d26903abd4f754c4b0f01240d5

The letters g and y are cut off on the bottom so the whole letter is not visible.

**Comment by chao-master** [comment]
Which browser are you using?

**Comment by MrQuallzin** [comment]
Google Chrome

**Comment by MrQuallzin** [comment]
It could be my version of Chrome being weird. I just tested it on Chrome on my phone and it looks fine.

**Comment by DanielOaks** [comment]
I can't recreate it here on Chrome or Firefox either. Might be a specific version of Chrome?

**Comment by chao-master** [comment]
Hmm @MrQuallzin What version of chrome are you using?

**Comment by MrQuallzin** [comment]
I am using Version 43.0.2357.124 m. After a little more experimenting, it seems that my zoom level affects it. When at 100% the letters are cut off, but when at different levels the letters are either whole or cut to varying degrees.

**Comment by chao-master** [comment]
Closing - could not be reproduced.
If the problem can be reproduced by another user feel free to reopen
