### ISSUE TITLE
Edit/view placeholder text overlaps on link-based load

### ISSUE THREAD

**Issue by coandco** [chao-master/TSSSFF-Generator#7]
As of c2566f9b0932432353d8cbb64b1125b6f40be811, if you load a card with the hash (example: http://ripppo.me/TSSSFF-Beta/#edit:4eaeeb1001d5efc3ffd03c63303fa1f0), the placeholder text for the "edit" and "view" boxes overlaps with their contents.  As soon as you click into the boxes and edit what's inside, it moves out of the way, but it still looks odd until you do so.

**Comment by chao-master** [comment]
Yeh I just noctied. It's an issue with material design for bootstrap. Will look into a fix.

**Comment by chao-master** [comment]
On closer inspect the Card image field does it, so it's not wholy bootstrap material
